/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee, Coin } from "@cosmjs/amino";
import { useMutation, UseMutationOptions } from "@tanstack/react-query";
import { Expiration, Timestamp, Uint64, AllNftInfoResponse, OwnerOfResponse, Approval, NftInfoResponseForNullable_Empty, Empty, ApprovalResponse, ApprovalsResponse, ContractInfoResponse, ExecuteMsg, Binary, MintMsgForNullable_Empty, InstantiateMsg, MinterResponse, NftInfoResponse, NumTokensResponse, OperatorsResponse, QueryMsgForEmpty, TokensResponse } from "./ArtistNft.types";
import { ArtistNftClient } from "./ArtistNft.client";
export interface ArtistNftExtensionMutation {
  client: ArtistNftClient;
  msg: {
    msg: Empty;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useArtistNftExtensionMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtistNftExtensionMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtistNftExtensionMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.extension(msg, fee, memo, funds), options);
}
export interface ArtistNftBurnMutation {
  client: ArtistNftClient;
  msg: {
    tokenId: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useArtistNftBurnMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtistNftBurnMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtistNftBurnMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.burn(msg, fee, memo, funds), options);
}
export interface ArtistNftMintMutation {
  client: ArtistNftClient;
  msg: {
    extension?: Empty;
    owner: string;
    tokenId: string;
    tokenUri?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useArtistNftMintMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtistNftMintMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtistNftMintMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.mint(msg, fee, memo, funds), options);
}
export interface ArtistNftRevokeAllMutation {
  client: ArtistNftClient;
  msg: {
    operator: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useArtistNftRevokeAllMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtistNftRevokeAllMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtistNftRevokeAllMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.revokeAll(msg, fee, memo, funds), options);
}
export interface ArtistNftApproveAllMutation {
  client: ArtistNftClient;
  msg: {
    expires?: Expiration;
    operator: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useArtistNftApproveAllMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtistNftApproveAllMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtistNftApproveAllMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.approveAll(msg, fee, memo, funds), options);
}
export interface ArtistNftRevokeMutation {
  client: ArtistNftClient;
  msg: {
    spender: string;
    tokenId: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useArtistNftRevokeMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtistNftRevokeMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtistNftRevokeMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.revoke(msg, fee, memo, funds), options);
}
export interface ArtistNftApproveMutation {
  client: ArtistNftClient;
  msg: {
    expires?: Expiration;
    spender: string;
    tokenId: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useArtistNftApproveMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtistNftApproveMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtistNftApproveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.approve(msg, fee, memo, funds), options);
}
export interface ArtistNftSendNftMutation {
  client: ArtistNftClient;
  msg: {
    contract: string;
    msg: Binary;
    tokenId: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useArtistNftSendNftMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtistNftSendNftMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtistNftSendNftMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.sendNft(msg, fee, memo, funds), options);
}
export interface ArtistNftTransferNftMutation {
  client: ArtistNftClient;
  msg: {
    recipient: string;
    tokenId: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useArtistNftTransferNftMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtistNftTransferNftMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtistNftTransferNftMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.transferNft(msg, fee, memo, funds), options);
}