/**
* This file was automatically generated by @jmes-cosmwasm/ts-codegen@0.14.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @jmes-cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Coin } from "@terra-money/terra.js";
import { useMutation, UseMutationOptions } from "@tanstack/react-query";
import { Expiration, Timestamp, Uint64, AllNftInfoResponse, OwnerOfResponse, Approval, NftInfoResponseForNullable_Empty, Empty, ApprovalResponse, ApprovalsResponse, ContractInfoResponse, ExecuteMsg, Binary, MintMsgForNullable_Empty, InstantiateMsg, MinterResponse, NftInfoResponse, NumTokensResponse, OperatorsResponse, QueryMsgForEmpty, TokensResponse } from "./ArtNft.types";
import { ArtNftClient } from "./ArtNft.client";
export interface ArtNftExtensionMutation {
  client: ArtNftClient;
  msg: {
    msg: Empty;
  };
  args?: {
    coins?: Coins;
  };
}
export function useArtNftExtensionMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtNftExtensionMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtNftExtensionMutation>(({
    client,
    msg,
    args: {
      coins
    } = {}
  }) => client.extension(msg, coins), options);
}
export interface ArtNftBurnMutation {
  client: ArtNftClient;
  msg: {
    tokenId: string;
  };
  args?: {
    coins?: Coins;
  };
}
export function useArtNftBurnMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtNftBurnMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtNftBurnMutation>(({
    client,
    msg,
    args: {
      coins
    } = {}
  }) => client.burn(msg, coins), options);
}
export interface ArtNftMintMutation {
  client: ArtNftClient;
  msg: MintMsgForNullable_Empty;
  args?: {
    coins?: Coins;
  };
}
export function useArtNftMintMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtNftMintMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtNftMintMutation>(({
    client,
    msg,
    args: {
      coins
    } = {}
  }) => client.mint(msg, coins), options);
}
export interface ArtNftRevokeAllMutation {
  client: ArtNftClient;
  msg: {
    operator: string;
  };
  args?: {
    coins?: Coins;
  };
}
export function useArtNftRevokeAllMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtNftRevokeAllMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtNftRevokeAllMutation>(({
    client,
    msg,
    args: {
      coins
    } = {}
  }) => client.revokeAll(msg, coins), options);
}
export interface ArtNftApproveAllMutation {
  client: ArtNftClient;
  msg: {
    expires?: Expiration;
    operator: string;
  };
  args?: {
    coins?: Coins;
  };
}
export function useArtNftApproveAllMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtNftApproveAllMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtNftApproveAllMutation>(({
    client,
    msg,
    args: {
      coins
    } = {}
  }) => client.approveAll(msg, coins), options);
}
export interface ArtNftRevokeMutation {
  client: ArtNftClient;
  msg: {
    spender: string;
    tokenId: string;
  };
  args?: {
    coins?: Coins;
  };
}
export function useArtNftRevokeMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtNftRevokeMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtNftRevokeMutation>(({
    client,
    msg,
    args: {
      coins
    } = {}
  }) => client.revoke(msg, coins), options);
}
export interface ArtNftApproveMutation {
  client: ArtNftClient;
  msg: {
    expires?: Expiration;
    spender: string;
    tokenId: string;
  };
  args?: {
    coins?: Coins;
  };
}
export function useArtNftApproveMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtNftApproveMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtNftApproveMutation>(({
    client,
    msg,
    args: {
      coins
    } = {}
  }) => client.approve(msg, coins), options);
}
export interface ArtNftSendNftMutation {
  client: ArtNftClient;
  msg: {
    contract: string;
    msg: Binary;
    tokenId: string;
  };
  args?: {
    coins?: Coins;
  };
}
export function useArtNftSendNftMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtNftSendNftMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtNftSendNftMutation>(({
    client,
    msg,
    args: {
      coins
    } = {}
  }) => client.sendNft(msg, coins), options);
}
export interface ArtNftTransferNftMutation {
  client: ArtNftClient;
  msg: {
    recipient: string;
    tokenId: string;
  };
  args?: {
    coins?: Coins;
  };
}
export function useArtNftTransferNftMutation(options?: Omit<UseMutationOptions<ExecuteResult, Error, ArtNftTransferNftMutation>, "mutationFn">) {
  return useMutation<ExecuteResult, Error, ArtNftTransferNftMutation>(({
    client,
    msg,
    args: {
      coins
    } = {}
  }) => client.transferNft(msg, coins), options);
}