/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Addr, ConfigResponse, ExecuteMsg, Uint128, Timestamp, Uint64, GrantResponse, GrantsResponse, Grant, InstantiateMsg, QueryMsg } from "./Distribution.types";
export interface DistributionReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  grant: ({
    grantId
  }: {
    grantId: number;
  }) => Promise<GrantResponse>;
  grants: ({
    dao,
    limit,
    startAfter
  }: {
    dao?: Addr;
    limit?: number;
    startAfter?: string;
  }) => Promise<GrantsResponse>;
}
export class DistributionQueryClient implements DistributionReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.grant = this.grant.bind(this);
    this.grants = this.grants.bind(this);
  }

  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  grant = async ({
    grantId
  }: {
    grantId: number;
  }): Promise<GrantResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      grant: {
        grant_id: grantId
      }
    });
  };
  grants = async ({
    dao,
    limit,
    startAfter
  }: {
    dao?: Addr;
    limit?: number;
    startAfter?: string;
  }): Promise<GrantsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      grants: {
        dao,
        limit,
        start_after: startAfter
      }
    });
  };
}
export interface DistributionInterface extends DistributionReadOnlyInterface {
  contractAddress: string;
  sender: string;
  addGrant: ({
    amount,
    dao,
    duration
  }: {
    amount: Uint128;
    dao: Addr;
    duration: number;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  claim: ({
    grantId
  }: {
    grantId: number;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export class DistributionClient extends DistributionQueryClient implements DistributionInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.addGrant = this.addGrant.bind(this);
    this.claim = this.claim.bind(this);
  }

  addGrant = async ({
    amount,
    dao,
    duration
  }: {
    amount: Uint128;
    dao: Addr;
    duration: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_grant: {
        amount,
        dao,
        duration
      }
    }, fee, memo, funds);
  };
  claim = async ({
    grantId
  }: {
    grantId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim: {
        grant_id: grantId
      }
    }, fee, memo, funds);
  };
}