/**
* This file was automatically generated by @jmes-cosmwasm/ts-codegen@0.14.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @jmes-cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export interface ConfigResponse {
  artist_curator_addr?: Addr | null;
  bjmes_token_addr: Addr;
  period_start_epoch: number;
  posting_period_length: number;
  proposal_required_deposit: Uint128;
  proposal_required_percentage: number;
  voting_period_length: number;
  [k: string]: unknown;
}
export type Cw20HookMsg = {
  text_proposal: {
    description: string;
    title: string;
    [k: string]: unknown;
  };
} | {
  request_feature: {
    description: string;
    feature: Feature;
    title: string;
    [k: string]: unknown;
  };
} | {
  funding: {
    amount: Uint128;
    description: string;
    duration: number;
    title: string;
    [k: string]: unknown;
  };
};
export type Feature = {
  artist_curator: {
    approved: number;
    duration: number;
    [k: string]: unknown;
  };
};
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  vote: {
    id: number;
    vote: VoteOption;
    [k: string]: unknown;
  };
} | {
  conclude: {
    id: number;
    [k: string]: unknown;
  };
} | {
  set_contract: {
    artist_curator: string;
    distribution: string;
    identityservice: string;
    [k: string]: unknown;
  };
};
export type Binary = string;
export type VoteOption = "yes" | "no";
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface InstantiateMsg {
  artist_curator_addr?: string | null;
  bjmes_token_addr: string;
  owner: string;
  period_start_epoch: number;
  posting_period_length: number;
  proposal_required_deposit: Uint128;
  proposal_required_percentage: number;
  voting_period_length: number;
  [k: string]: unknown;
}
export type ProposalPeriod = "posting" | "voting";
export interface PeriodInfoResponse {
  current_block: number;
  current_period: ProposalPeriod;
  current_posting_start: number;
  current_time_in_cycle: number;
  current_voting_end: number;
  current_voting_start: number;
  cycle_length: number;
  next_posting_start: number;
  next_voting_start: number;
  posting_period_length: number;
  voting_period_length: number;
  [k: string]: unknown;
}
export type ProposalType = {
  text: {
    [k: string]: unknown;
  };
} | {
  feature_request: Feature;
} | {
  funding: {
    [k: string]: unknown;
  };
};
export type ProposalStatus = "posted" | "voting" | "success" | "expired" | "success_concluded" | "expired_concluded";
export interface ProposalResponse {
  coins_no: Uint128;
  coins_yes: Uint128;
  concluded: boolean;
  dao: Addr;
  deposit_amount: Uint128;
  description: string;
  id: number;
  no_voters: Addr[];
  posting_start: number;
  prop_type: ProposalType;
  start_block: number;
  status: ProposalStatus;
  title: string;
  voting_end: number;
  voting_start: number;
  yes_voters: Addr[];
  [k: string]: unknown;
}
export interface ProposalsResponse {
  proposal_count: number;
  proposals: ProposalResponse[];
  [k: string]: unknown;
}
export type QueryMsg = {
  config: {
    [k: string]: unknown;
  };
} | {
  period_info: {
    [k: string]: unknown;
  };
} | {
  proposal: {
    id: number;
    [k: string]: unknown;
  };
} | {
  proposals: {
    limit?: number | null;
    start?: number | null;
    [k: string]: unknown;
  };
};