/**
* This file was automatically generated by @jmes-cosmwasm/ts-codegen@0.14.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @jmes-cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface DaosResponse {
  daos: [number, Addr][];
  [k: string]: unknown;
}
export type ExecuteMsg = {
  register_user: {
    name: string;
    [k: string]: unknown;
  };
} | {
  register_dao: DaoInstantiateMsg;
};
export type Duration = {
  height: number;
} | {
  time: number;
};
export type Threshold = {
  absolute_count: {
    weight: number;
  };
} | {
  absolute_percentage: {
    percentage: Decimal;
  };
} | {
  threshold_quorum: {
    quorum: Decimal;
    threshold: Decimal;
  };
};
export type Decimal = string;
export interface DaoInstantiateMsg {
  dao_name: string;
  max_voting_period: Duration;
  threshold: Threshold;
  voters: Voter[];
}
export interface Voter {
  addr: string;
  weight: number;
  [k: string]: unknown;
}
export type IdType = "user" | "dao";
export interface GetIdentityByNameResponse {
  identity?: Identity | null;
  [k: string]: unknown;
}
export interface Identity {
  id_type: IdType;
  name: string;
  owner: Addr;
  [k: string]: unknown;
}
export interface GetIdentityByOwnerResponse {
  identity?: Identity | null;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  dao_code_id: number;
  owner: Addr;
  [k: string]: unknown;
}
export type QueryMsg = {
  get_identity_by_owner: {
    owner: string;
    [k: string]: unknown;
  };
} | {
  get_identity_by_name: {
    name: string;
    [k: string]: unknown;
  };
} | {
  daos: {
    limit?: number | null;
    order?: Ordering | null;
    start_after?: number | null;
    [k: string]: unknown;
  };
};
export type Ordering = "ascending" | "descending";