/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./ArtNft.types";
import * as _1 from "./ArtNft.client";
import * as _2 from "./ArtNft.react-query";
import * as _3 from "./ArtistCurator.types";
import * as _4 from "./ArtistCurator.client";
import * as _5 from "./ArtistCurator.react-query";
import * as _6 from "./ArtistNft.types";
import * as _7 from "./ArtistNft.client";
import * as _8 from "./ArtistNft.react-query";
import * as _9 from "./BjmesToken.types";
import * as _10 from "./BjmesToken.client";
import * as _11 from "./BjmesToken.react-query";
import * as _12 from "./DaoMembers.types";
import * as _13 from "./DaoMembers.client";
import * as _14 from "./DaoMembers.react-query";
import * as _15 from "./DaoMultisig.types";
import * as _16 from "./DaoMultisig.client";
import * as _17 from "./DaoMultisig.react-query";
import * as _18 from "./Distribution.types";
import * as _19 from "./Distribution.client";
import * as _20 from "./Distribution.react-query";
import * as _21 from "./Governance.types";
import * as _22 from "./Governance.client";
import * as _23 from "./Governance.react-query";
import * as _24 from "./Identityservice.types";
import * as _25 from "./Identityservice.client";
import * as _26 from "./Identityservice.react-query";
export namespace contracts {
  export const ArtNft = { ..._0,
    ..._1,
    ..._2
  };
  export const ArtistCurator = { ..._3,
    ..._4,
    ..._5
  };
  export const ArtistNft = { ..._6,
    ..._7,
    ..._8
  };
  export const BjmesToken = { ..._9,
    ..._10,
    ..._11
  };
  export const DaoMembers = { ..._12,
    ..._13,
    ..._14
  };
  export const DaoMultisig = { ..._15,
    ..._16,
    ..._17
  };
  export const Distribution = { ..._18,
    ..._19,
    ..._20
  };
  export const Governance = { ..._21,
    ..._22,
    ..._23
  };
  export const Identityservice = { ..._24,
    ..._25,
    ..._26
  };
}